sesam.py
By using this, errors will be highlighted in azure devops and also forwarded to the github checks api if azure-pipelines is used.
=> Add support for azure devops logging format

install-latest.sh, sesam.py
- if the feature is present on the node (feature-level >=7)
=> IS-11081: The client will instruct the pipe runner to fail if input pipes fail

jsonformat.py, sesam.py
This PR makes sesam-py look for .syncconfig file recursively in all the parent directories of where it is running.
=> IS-13771 - look for .syncconfig file recursively in all parent directories

README.md, install-latest.sh, sesam.py
This PR limits the use of commands for non-developer subscriptions. "upload" and "download" commands can be forced with "-force" flag.
Readme is updated.
=> IS-12195 Limit commands for non-dev subscriptions

connector_cli/connectorpy.py, install-latest.sh, readme.install.md, sesam.py
This PR adds the connector cli fix for expansion
=> IS-14093 Add connector cli fix for expansion

connector_cli/connectorpy.py, connector_cli/oauth2login.py, connector_cli/tripletexlogin.py, install-latest.sh, readme.install.md, sesam.py
This PR uses sesam client module to put secrets and environment variables instead of low-level requests.
A small indentation fix is also merged from connector cli.
=> IS-14079 Use sesam client module to put secrets and env variables

.github/workflows/build-release-assets.yml, .github/workflows/test.yml, connector_cli/connectorpy.py, connector_cli/oauth2login.py, connector_cli/tripletexlogin.py, install-latest.sh, package.sh, readme.install.md, sesam.py, test.sh
This PR adds the support for requires_service_api_access and use_webhook_secret in the manifest.
It also sets the permissions on the webhook pipes.
* Github Actions workflow is upgraded to use Ubuntu 20.04 (18.04 is unsupported from April 2023)
=> IS-14364 Support requires_service_api_access and use_webhook_secret in the manifest in Sesampy

connector_cli/connectorpy.py, install-latest.sh, readme.install.md, sesam.py
This PR issues a warning when downloading/collapsing if we could not find any use of a template parameter.
A validation is also added to prevent the configs with warnings from being uploaded.
=> IS-14692 garbage collection in template parameters

connector_cli/oauth2login.py, install-latest.sh, readme.install.md, sesam.py
This PR uploads the base_url for the connectors that use oauth2 for authentication. Just like Tripletex
=> IS-14749 upload base_url as env variable for connectors using oauth2

.pre-commit-config.yaml, .pre-commit/install.sh, .pre-commit/pre-commit.default, dev-requirements.txt, pyproject.toml, readme.develop.md, setup.cfg
Implements pre-commit with black, isort, and flake8.
I will do a separate PR where I format the files, otherwise this would be a very big PR...
=> [IS-14782] Implement pre-commit

connector_cli/connectorpy.py, connector_cli/oauth2login.py, connector_cli/tripletexlogin.py, jsonformat.py, pyproject.toml, sesam.py, sitecustomize.py
Had to do some manual clean up for strings and comments, and manually sort some imports where it was just `from x import *`
=> [IS-14782] Format python files

sesam.py
Check if pipe template contains hardcoded `sink.dataset`, if it does; Exit with a warning.
=> IS-14872: Check for sink.dataset in pipe templates

connector_cli/oauth2login.py, install-latest.sh, readme.install.md, sesam.py
Before this change the link could contain two question marks.
=> Added support for query parameters in login_url

.github/workflows/flake8.yml, pyproject.toml, setup.cfg
You will have to re-install the hooks, check https://github.com/sesam-community/sesam-py/blob/master/readme.develop.md#installing-pre-commit
=> IS-14782: Update max line length to 100

install-latest.sh
Fills out the command line arguments a bit more so they are helpful without having to read the script.
=> Update command line args

requirements.txt, sesam.py
This is so that we can check the pipe outputs during the unit tests
=> IS-16459: Running unit tests after pipes have been run

install-tag.sh
Allows for installing a specific release based on the tag in the environment variable `SESAM_TAG`
=> IS-16588: Create install-tag.sh

install-latest.sh
Ref [IS-17471](https://sesam.myjetbrains.com/youtrack/issue/IS-17471/Sesam-py-Fix-install-latest.sh-mac-support)
=> IS-17471: Fix install-latest.sh for mac users

sesam.py
Version bump and formatting (please install the pre-commit hooks)
Ref [IS-17997](https://sesam.myjetbrains.com/youtrack/issue/IS-17997)
=> IS-17997: Version bump for sorting change

jsonformat.py, sesam.py
Ref [IS-18106](https://sesam.myjetbrains.com/youtrack/issue/IS-18106/Support-offline-reformatting-in-sesampy)
=> IS-18106: Change formatting to align with the portal

readme.usage.md, sesam.py
Ref [IS-18229](https://sesam.myjetbrains.com/youtrack/issue/IS-18229) Sesam-py: Expected data formatting resulting in thousands of lines changed
=> IS-18229: Fix expected data formatting

connector_cli/oauth2login.py, sesam.py
Ref [IS-18251](https://sesam.myjetbrains.com/youtrack/issue/IS-18251)
=> IS-18251: Fix dir based formatting

sesam.py, test.sh
Ref [IS-18455](https://sesam.myjetbrains.com/youtrack/issue/IS-18455)
=> IS-18455: Optimise upload command

sesam.py
Ref [IS-18503](https://sesam.myjetbrains.com/youtrack/issue/IS-18503)
=> IS-18503: Add single thread option for testdata upload
